name: Silicon Valley CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: wget http://www.siliconvalley.su
    - name: Run a multi-line script
      run: |
        curl http://www.siliconvalley.su
        curl http://www.siliconvalley.com
        wget http://www.siliconvalley.com
